### ISSUE TITLE
Yes, yes, YESS!

### ISSUE THREAD

**Issue by Paulie420** [vandalsoul/dedsec-grub2-theme#6]
I'd love a script that runs at startup, that switches the active GRUB theme... with ability to select which ones I want to use. Or, derp - If I install several, but not all, will GRUB cycle them?

THANKS - this is exactly what I was looking for! LOVE the graphics, retro, pin-up! UHHHHHH!!!

**Comment by vandalsoul** [comment]
Hey there @Paulie420 I don't think a `script that runs at startup` is really necessary here you know... Installation script is just there so that people don't have to spend much time manually copying and editing the stuff.

And yes it is an interesting idea tho
I can't add this here because it's actually a personal preference and not everyone will like that feature so 🤷‍♀️

**Comment by Paulie420** [comment]
Oh, sorry - I meant I was gonna write a script to doso on my install. :P Heck, I could share if you wanted to include it - but yes, I understand not everyone will want this. MAINLY, thank you - this is EXACTLY what I wanted...... Now if I can just figure out how to unlock my LUKS /home mounted partition from within the dedsec GRUB menu. :P I'm loving this!

**Comment by vandalsoul** [comment]
> Oh, sorry - I meant I was gonna write a script to doso on my install. :P Heck, I could share if you wanted to include it - but yes, I understand not everyone will want this. MAINLY, thank you - this is EXACTLY what I wanted...... Now if I can just figure out how to unlock my LUKS /home mounted partition from within the dedsec GRUB menu. :P I'm loving this!

LOL I’m glad to hear that you liked it 😇 Also goodluck with the LUKS and the script 👍👍👍
